name: Build and Push 
on :
    push:
        branches: [main]
    pull_request:
        branches: [main]
    
jobs:
    build_and_push:
        name: Build Docker image and push it
        runs-on: ubuntu:latest
        steps:
          - 
            name: Checkout
            uses: actions/checkout@v3

          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Log in to the Container Registry
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}
          
          - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: ./task
                file: ./task4/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/local548:latest
                
          -
            name: Image build output
            run: echo ${{steps.docker_build.outputs.digest}}
